title: Felgona Awuor Owuor
description: Data Analyst | Economics & Statistics | Monitoring, Evaluation & Learning (MEL)
theme: minima

collections:
  projects:
    output: true
nav:
  - name: About
    link: /
  - name: Projects
    link: /projects
  - name: Skills
    link: /skills
  - name: Contact
    link: /contact

    markdown: kramdown
sass:
  style: compressed
